### ISSUE TITLE
Unknown error: No such file: ./ver10/device/wsdl/devicemgmt.wsdl

### ISSUE THREAD

**Issue by Kyrw** [FalkTannhaeuser/python-onvif-zeep#130]
I'm having this issue when instantiating a ONVIFCAMERA. 

I installed python onvif zeep with 
`pip install --upgrade onvif_zeep` on the  ./venv of my project

if I run

`mycam = ONVIFCamera(IP, PORT, USER,  PASS) `

I get the following error: 

`onvif2.exceptions.ONVIFError: Unknown error: No such file: /home/***/.venv/lib/python3.11/site-packages/wsdl/./ver10/device/wsdl/devicemgmt.wsdl`

After looking around, I found another Lib inside my ./venv with capital L. The file devicemgmt.wsdl is inside this path, but the library seems to be adding this `./ver10/device/wsdl/devicemgmt.wsdl` to the file path, that, to me, doesnt make sense.

The result changing the path to this directory is similtar: 
`mycam = ONVIFCamera(IP, PORT, USER,  PASS, wsdl_dir = '/home/***/.venv/Lib/site-packages/wsdl/')`

`onvif2.exceptions.ONVIFError: Unknown error: No such file: /home/***/.venv/Lib/site-packages/wsdl/./ver10/device/wsdl/devicemgmt.wsdl`

How do i handle this? I even tried on a windows 11 machine, and the same problem with the appended path is happening.

**Comment by ltomes** [comment]
I'm seeing the same behavior. I am trying to use `python-onvif-zeep` in the context of this script: https://gist.githubusercontent.com/hawkeye217/152a1d4ba80760dac95d46e143d37112/raw/b40ff52c89cf8412dcf3be1635e2f549e36f135c/fovtest.py

**Comment by attila-lendvai** [comment]
probably i'm seeing the same, or something closely related.

i get this error when trying to:

```
$ ./bin/onvif-cli --host doorbell.lan --port 8000 --user admin --password *** service
Traceback (most recent call last):
  File "~/workspace/onvif/./bin/onvif-cli", line 33, in <module>
    sys.exit(load_entry_point('onvif-zeep==0.2.12', 'console_scripts', 'onvif-cli')())
  File "~/workspace/onvif/lib/python3.10/site-packages/onvif_zeep-0.2.12-py3.10.egg/onvif/cli.py", line 159, in main
    cli.setup(args)
  File "~/workspace/onvif/lib/python3.10/site-packages/onvif_zeep-0.2.12-py3.10.egg/onvif/cli.py", line 36, in setup
    self.client = ONVIFCamera(args.host, args.port,
  File "~/workspace/onvif/lib/python3.10/site-packages/onvif_zeep-0.2.12-py3.10.egg/onvif/client.py", line 223, in __init__
    self.update_xaddrs()
  File "~/workspace/onvif/lib/python3.10/site-packages/onvif_zeep-0.2.12-py3.10.egg/onvif/client.py", line 230, in update_xaddrs
    self.devicemgmt = self.create_devicemgmt_service()
  File "~/workspace/onvif/lib/python3.10/site-packages/onvif_zeep-0.2.12-py3.10.egg/onvif/client.py", line 364, in create_devicemgmt_service
    return self.create_onvif_service('devicemgmt', transport=transport)
  File "~/workspace/onvif/lib/python3.10/site-packages/onvif_zeep-0.2.12-py3.10.egg/onvif/client.py", line 341, in create_onvif_service
    xaddr, wsdl_file, binding_name = self.get_definition(name, portType)
  File "~/workspace/onvif/lib/python3.10/site-packages/onvif_zeep-0.2.12-py3.10.egg/onvif/client.py", line 312, in get_definition
    raise ONVIFError('No such file: %s' % wsdlpath)
onvif.exceptions.ONVIFError: Unknown error: No such file: ~/workspace/onvif/lib/python3.10/site-packages/onvif_zeep-0.2.12-py3.10.egg/wsdl/devicemgmt.wsdl
```

while i do have this file (notice the superfluous `/lib/python3.10/site-packages/` in the path in the error):
```
$ ll ~/workspace/onvif/lib/python3.10/site-packages/onvif_zeep-0.2.12-py3.10.egg/lib/python3.10/site-packages/wsdl/devicemgmt.wsdl
-rw-r--r-- 1 alendvai users 163209 Apr  1 22:51 ~/workspace/onvif/lib/python3.10/site-packages/onvif_zeep-0.2.12-py3.10.egg/lib/python3.10/site-packages/wsdl/devicemgmt.wsdl

```
