### ISSUE TITLE
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1

### ISSUE THREAD

**Issue by Ideasrefined** [FalkTannhaeuser/python-onvif-zeep#29]
I am getting the following exception when I try to run streaming.py. I get this exception for any example or test code I try.
```
Traceback (most recent call last):
  File "/home/enigma/codes/python/virtualEnvironment/env/lib/python3.6/site-packages/zeep/loader.py", line 50, in parse_xml
    forbid_entities=settings.forbid_entities)
  File "/home/enigma/codes/python/virtualEnvironment/env/lib/python3.6/site-packages/defusedxml/lxml.py", line 143, in fromstring
    rootelement = _etree.fromstring(text, parser, base_url=base_url)
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1765, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/enigma/codes/python/virtualEnvironment/env/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 170, in process_reply
    doc = parse_xml(content, self.transport, settings=client.settings)
  File "/home/enigma/codes/python/virtualEnvironment/env/lib/python3.6/site-packages/zeep/loader.py", line 54, in parse_xml
    content=content
zeep.exceptions.XMLSyntaxError: Invalid XML content received (Document is empty, line 1, column 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/enigma/codes/python/virtualEnvironment/env/lib/python3.6/site-packages/onvif_zeep-0.2.12-py3.6.egg/onvif/client.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "/home/enigma/codes/python/virtualEnvironment/env/lib/python3.6/site-packages/onvif_zeep-0.2.12-py3.6.egg/onvif/client.py", line 153, in wrapped
    return call(params, callback)
  File "/home/enigma/codes/python/virtualEnvironment/env/lib/python3.6/site-packages/onvif_zeep-0.2.12-py3.6.egg/onvif/client.py", line 140, in call
    ret = func(**params)
  File "/home/enigma/codes/python/virtualEnvironment/env/lib/python3.6/site-packages/zeep/proxy.py", line 42, in __call__
    self._op_name, args, kwargs)
  File "/home/enigma/codes/python/virtualEnvironment/env/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 132, in send
    return self.process_reply(client, operation_obj, response)
  File "/home/enigma/codes/python/virtualEnvironment/env/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 176, in process_reply
    content=response.content)
zeep.exceptions.TransportError: Server returned response (200) with invalid XML: Invalid XML content received (Document is empty, line 1, column 1).
Content: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "streaming.py", line 58, in <module>
    media_profile_configuration()
  File "streaming.py", line 12, in media_profile_configuration
    mycam = ONVIFCamera('192.168.1.52', 80, 'admin', 'admin')
  File "/home/enigma/codes/python/virtualEnvironment/env/lib/python3.6/site-packages/onvif_zeep-0.2.12-py3.6.egg/onvif/client.py", line 216, in __init__
    self.update_xaddrs()
  File "/home/enigma/codes/python/virtualEnvironment/env/lib/python3.6/site-packages/onvif_zeep-0.2.12-py3.6.egg/onvif/client.py", line 233, in update_xaddrs
    capabilities = self.devicemgmt.GetCapabilities({'Category': 'All'})
  File "/home/enigma/codes/python/virtualEnvironment/env/lib/python3.6/site-packages/onvif_zeep-0.2.12-py3.6.egg/onvif/client.py", line 26, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: Server returned response (200) with invalid XML: Invalid XML content received (Document is empty, line 1, column 1).
Content: b''
```

**Comment by bphillips09** [comment]
Same issue here
