### ISSUE TITLE
onvif.exceptions.ONVIFError: Unknown error: Sender not authorized

### ISSUE THREAD

**Issue by lygoon** [FalkTannhaeuser/python-onvif-zeep#90]
problem： onvif.exceptions.ONVIFError: Unknown error: Sender not authorized
I have the problem, how can I solve it? And I have enabled onvif and created a administrator user in my camera. Thank you~

Here is the detailed information below:

Traceback (most recent call last):
  File "/home/lygoon/miniconda3/lib/python3.8/site-packages/onvif_zeep-0.2.12-py3.8.egg/onvif/client.py", line 25, in wrapped
    return func(*args, **kwargs)
  File "/home/lygoon/miniconda3/lib/python3.8/site-packages/onvif_zeep-0.2.12-py3.8.egg/onvif/client.py", line 150, in wrapped
    return call(params, callback)
  File "/home/lygoon/miniconda3/lib/python3.8/site-packages/onvif_zeep-0.2.12-py3.8.egg/onvif/client.py", line 138, in call
    ret = func(**params)
  File "/home/lygoon/miniconda3/lib/python3.8/site-packages/zeep-4.1.0-py3.8.egg/zeep/proxy.py", line 46, in __call__
    return self._proxy._binding.send(
  File "/home/lygoon/miniconda3/lib/python3.8/site-packages/zeep-4.1.0-py3.8.egg/zeep/wsdl/bindings/soap.py", line 135, in send
    return self.process_reply(client, operation_obj, response)
  File "/home/lygoon/miniconda3/lib/python3.8/site-packages/zeep-4.1.0-py3.8.egg/zeep/wsdl/bindings/soap.py", line 229, in process_reply
    return self.process_error(doc, operation)
  File "/home/lygoon/miniconda3/lib/python3.8/site-packages/zeep-4.1.0-py3.8.egg/zeep/wsdl/bindings/soap.py", line 391, in process_error
    raise Fault(
zeep.exceptions.Fault: Sender not authorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "continuous_move.py", line 145, in <module>
    setup_move()
  File "continuous_move.py", line 75, in setup_move
    mycam = ONVIFCamera(IP, PORT, USER, PASS) 
  File "/home/lygoon/miniconda3/lib/python3.8/site-packages/onvif_zeep-0.2.12-py3.8.egg/onvif/client.py", line 215, in __init__
    self.update_xaddrs()
  File "/home/lygoon/miniconda3/lib/python3.8/site-packages/onvif_zeep-0.2.12-py3.8.egg/onvif/client.py", line 232, in update_xaddrs
    capabilities = self.devicemgmt.GetCapabilities({'Category': 'All'})
  File "/home/lygoon/miniconda3/lib/python3.8/site-packages/onvif_zeep-0.2.12-py3.8.egg/onvif/client.py", line 27, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: Sender not authorized

**Comment by AmbarishGK1** [comment]
You can close this issue @lygoon since you have solved it here
[https://github.com/FalkTannhaeuser/python-onvif-zeep/issues/42](https://github.com/FalkTannhaeuser/python-onvif-zeep/issues/42)

**Comment by winkmichael** [comment]
Did anyone ever solve this, same issue only with one axis camera
