### ISSUE TITLE
How to get Metadata in python ONVIF? (Service has no operation `GetSupportedMetadata`)

### ISSUE THREAD

**Issue by Oh-JongJin** [FalkTannhaeuser/python-onvif-zeep#95]
![image](https://user-images.githubusercontent.com/45455262/185064010-ba1e7b60-088a-4b24-98e7-5dd0acbd2e6c.png)

Currently, I'm looking for metadata access functions using the in Python-onvif. I want to get the coordinates of "BoundingBox" inside the red box. How to i access data?

https://www.onvif.org/ver20/analytics/wsdl/analytics.wsdl#op.GetSupportedMetadata
This function was used, but an `AttributeError` occurred.

```python
from onvif import ONVIFCamera

cam = ONVIFCamera('192.168.100.133', 80, 'ID', 'P/W')
cam.create_analytics_service()

meta = cam.analytics.GetSupportedMetadata()
print(meta)
```

result:
```bash
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\py310\lib\site-packages\zeep\proxy.py", line 97, in __getitem__
    return self._operations[key]
KeyError: 'GetSupportedMetadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\JetBrains\PyCharmCE2021.2\scratches\meta_data.py", line 24, in <module>
    meta = cam.analytics.GetSupportedMetadata()
  File "C:\Users\User\anaconda3\envs\py310\lib\site-packages\onvif\client.py", line 167, in __getattr__
    return self.service_wrapper(getattr(self.ws_client, name))
  File "C:\Users\User\anaconda3\envs\py310\lib\site-packages\zeep\proxy.py", line 88, in __getattr__
    return self[key]
  File "C:\Users\User\anaconda3\envs\py310\lib\site-packages\zeep\proxy.py", line 99, in __getitem__
    raise AttributeError("Service has no operation %r" % key)
AttributeError: Service has no operation 'GetSupportedMetadata'
```

I need your help.

**Comment by YahiaIono** [comment]
Is there any solution for this issue ?

**Comment by kaburagisec** [comment]
Use this code:

```python
from onvif import ONVIFClient

client = ONVIFClient('192.168.100.133', 80, 'ID', 'P/W')
analytics_service = client.analytics()

print(analytics_service.GetSupportedMetadata())
```

This script uses the [onvif-python](https://github.com/nirsimetri/onvif-python) library which uses the official wsdl from [onvif/specs](https://github.com/onvif/specs)

**Comment by kaburagisec** [comment]
Based on my reading, the WSDL folders (https://github.com/FalkTannhaeuser/python-onvif-zeep/blob/zeep/wsdl/analytics.wsdl) included in this library do not include the `GetSupportedMetadata` operation, which is because this library uses the outdated onvif wsdl.
